/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-dim': '#d73357',
        'on-error': '#490013',
        'secondary-dim': '#2de3ac',
        'on-secondary-fixed': '#00412e',
        'on-tertiary-fixed-variant': '#780021',
        'tertiary-fixed-dim': '#ff7986',
        'outline-variant': '#474754',
        'surface-dim': '#0d0d18',
        outline: '#757482',
        'on-tertiary-fixed': '#39000b',
        'inverse-on-surface': '#555461',
        'tertiary-fixed': '#ff9099',
        'primary-dim': '#8a4cfc',
        'on-primary-fixed': '#000000',
        'on-primary-container': '#2e006c',
        'on-secondary-fixed-variant': '#006046',
        primary: '#bd9dff',
        'on-surface-variant': '#aba9b9',
        'on-tertiary': '#490010',
        secondary: '#45f2b9',
        'secondary-container': '#006c4f',
        'secondary-fixed': '#45f2b9',
        'on-secondary-container': '#e0ffee',
        'inverse-primary': '#742fe5',
        'primary-container': '#b28cff',
        'on-error-container': '#ffb2b9',
        'surface-container-lowest': '#000000',
        'error-container': '#a70138',
        'on-tertiary-container': '#100001',
        'surface-container': '#181826',
        background: '#0d0d18',
        'tertiary-dim': '#ff6f7e',
        surface: '#0d0d18',
        'primary-fixed': '#b28cff',
        error: '#ff6e84',
        'surface-container-high': '#1e1e2d',
        'on-primary': '#3c0089',
        'surface-container-highest': '#242434',
        'on-surface': '#e9e6f7',
        'on-secondary': '#00563e',
        'tertiary-container': '#fc4563',
        'surface-container-low': '#12121e',
        'primary-fixed-dim': '#a67aff',
        'on-primary-fixed-variant': '#390083',
        'inverse-surface': '#fcf8ff',
        'surface-bright': '#2b2a3c',
        'surface-tint': '#bd9dff',
        tertiary: '#ff6f7e',
        'secondary-fixed-dim': '#2de3ac',
        'surface-variant': '#242434',
        'on-background': '#e9e6f7',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
